site_name: Socrates site
author: Honza
posts_per_page: 5
url: http://example.com
date_format: "%B %d, %Y"
text_processor: markdown
templates: django
append_slash: false
url_include_day: false
max_posts_for_feed: 10